### PR TITLE
Fix: Ensure bundled dependencies are correct (fixes #8)

### LINKED ISSUE #8: Ensure clean build environment before release
Currently, we do only an `npm update` during release, but this can lead to errors with bundling:
https://github.com/eslint/eslint/issues/5680

It would be better to completely remove `node_modules` and install using `--production` to ensure that the correct packages are included.

### PR DESCRIPTION
**Pull request by nzakas**

### CODE REVIEW

**Comment by ilyavolodin** [comment]
LGTM

File: lib/release-ops.js [hunk 1]
```diff
@@ -349,7 +355,7 @@ function release(prereleaseId) {
     ShellOps.exec("bundle-dependencies update");
 
     console.log("Committing to git");
-    ShellOps.exec("git add .");
+    ShellOps.exec("git add CHANGELOG.md package.json");
```
Comment (btmills) [inline lib/release-ops.js]: Thank you. This will prevent a whole category of mistakes. :+1:
